import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { toast } from "sonner";
import {
  Download,
  Sparkles,
  ScanLine,
  Wand2,
  ShieldCheck,
  Accessibility,
  Bot,
  Zap,
  Lock,
  Github,
} from "lucide-react";
import heroImg from "@/assets/hero.jpg";
import logo from "@/assets/logo.png";

const features = [
  {
    icon: ScanLine,
    title: "Smart page scan",
    body: "Detects every input, textarea, select, radio and checkbox — including ARIA-labelled controls.",
  },
  {
    icon: Wand2,
    title: "AI form filling",
    body: "Context-aware values generated by our Umabonakude agent on Hugging Face. One click, done.",
  },
  {
    icon: Accessibility,
    title: "Accessibility audit",
    body: "Spot missing alt text, unlabelled fields, empty links and heading issues — instantly.",
  },
  {
    icon: Bot,
    title: "Dual-agent system",
    body: "Blue agent for fast scans, Red agent for deep reasoning. Graceful fallbacks built in.",
  },
  {
    icon: Lock,
    title: "Local-first profile",
    body: "Your profile never leaves your browser unless you fill a field with it. No accounts, no tracking.",
  },
  {
    icon: Zap,
    title: "Works on any site",
    body: "Manifest V3, content script + service worker, runs on every URL with permission.",
  },
];

const steps = [
  "Download and unzip the extension.",
  "Open chrome://extensions in Chrome (or Edge / Brave / Arc).",
  "Toggle Developer mode in the top-right.",
  "Click Load unpacked and select the unzipped folder.",
  "Pin the Umabonakude icon, open any form, and hit Fill.",
];

export default function Index() {
  const [downloading, setDownloading] = useState(false);

  useEffect(() => {
    document.title =
      "Umabonakude — AI Form Filler & Accessibility Chrome Extension";
    const desc =
      "Free Chrome extension that scans web forms and fills them with AI. Built-in accessibility audit, no account required.";
    let m = document.querySelector('meta[name="description"]');
    if (!m) {
      m = document.createElement("meta");
      m.setAttribute("name", "description");
      document.head.appendChild(m);
    }
    m.setAttribute("content", desc);
  }, []);

  const download = () => {
    setDownloading(true);
    fetch("/umabonakude-extension.zip")
      .then((r) => {
        if (!r.ok) throw new Error(`Download failed (${r.status})`);
        return r.blob();
      })
      .then((blob) => {
        const a = document.createElement("a");
        a.href = URL.createObjectURL(blob);
        a.download = "umabonakude-extension.zip";
        a.click();
        URL.revokeObjectURL(a.href);
        toast.success("Download started", {
          description: "Unzip and load it as an unpacked extension.",
        });
      })
      .catch((e) => toast.error(e.message))
      .finally(() => setDownloading(false));
  };

  return (
    <div className="min-h-screen bg-background text-foreground">
      {/* Nav */}
      <header className="container flex items-center justify-between py-6">
        <a href="/" className="flex items-center gap-2">
          <img src={logo} alt="" width={32} height={32} className="rounded-lg" />
          <span className="font-semibold tracking-tight">Umabonakude</span>
        </a>
        <nav className="hidden gap-8 text-sm text-muted-foreground md:flex">
          <a href="#features" className="hover:text-foreground transition-colors">Features</a>
          <a href="#install" className="hover:text-foreground transition-colors">Install</a>
          <a href="#how" className="hover:text-foreground transition-colors">How it works</a>
        </nav>
        <Button onClick={download} disabled={downloading} size="sm" className="bg-gradient-primary shadow-elegant">
          <Download className="mr-2 h-4 w-4" />
          {downloading ? "Preparing…" : "Download"}
        </Button>
      </header>

      {/* Hero */}
      <section className="bg-gradient-hero">
        <div className="container grid gap-12 py-20 lg:grid-cols-2 lg:py-28">
          <div className="flex flex-col justify-center">
            <span className="inline-flex w-fit items-center gap-2 rounded-full border border-border bg-card/50 px-3 py-1 text-xs text-muted-foreground backdrop-blur">
              <Sparkles className="h-3 w-3 text-accent" />
              AI-powered Chrome extension · Manifest V3
            </span>
            <h1 className="mt-6 text-balance text-5xl font-bold tracking-tight md:text-6xl">
              Fill any web form
              <span className="block bg-gradient-text bg-clip-text text-transparent">
                with one click.
              </span>
            </h1>
            <p className="mt-6 max-w-xl text-lg text-muted-foreground">
              Umabonakude scans the page, understands every field, and fills the
              whole form using your local profile — powered by an AI agent
              hosted on Hugging Face. No API keys. No accounts.
            </p>
            <div className="mt-8 flex flex-wrap gap-3">
              <Button onClick={download} size="lg" className="bg-gradient-primary shadow-elegant">
                <Download className="mr-2 h-5 w-5" />
                Download extension
              </Button>
              <Button variant="outline" size="lg" asChild>
                <a href="#how">See how it works</a>
              </Button>
            </div>
            <div className="mt-8 flex items-center gap-6 text-sm text-muted-foreground">
              <div className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-accent" /> Local-first</div>
              <div className="flex items-center gap-2"><Zap className="h-4 w-4 text-accent" /> Works offline (fallback)</div>
              <div className="flex items-center gap-2"><Accessibility className="h-4 w-4 text-accent" /> WCAG aware</div>
            </div>
          </div>

          <div className="relative">
            <div className="absolute inset-0 -z-10 bg-gradient-primary opacity-30 blur-3xl" />
            <img
              src={heroImg}
              alt="Glowing AI orb scanning a holographic web form"
              width={1536}
              height={1024}
              className="rounded-2xl border border-border shadow-elegant"
            />
          </div>
        </div>
      </section>

      {/* Features */}
      <section id="features" className="container py-24">
        <div className="mx-auto max-w-2xl text-center">
          <h2 className="text-4xl font-bold tracking-tight">Built for the messy real web.</h2>
          <p className="mt-4 text-muted-foreground">
            From multi-step intake forms to clunky internal tools — Umabonakude reads what's there, then fills it intelligently.
          </p>
        </div>
        <div className="mt-14 grid gap-6 md:grid-cols-2 lg:grid-cols-3">
          {features.map((f) => (
            <Card key={f.title} className="group relative overflow-hidden border-border bg-card p-6 transition-all hover:-translate-y-1 hover:shadow-elegant">
              <div className="mb-4 inline-flex h-11 w-11 items-center justify-center rounded-xl bg-gradient-primary text-primary-foreground shadow-soft">
                <f.icon className="h-5 w-5" />
              </div>
              <h3 className="text-lg font-semibold">{f.title}</h3>
              <p className="mt-2 text-sm text-muted-foreground">{f.body}</p>
            </Card>
          ))}
        </div>
      </section>

      {/* How it works */}
      <section id="how" className="border-y border-border bg-card/30">
        <div className="container grid gap-12 py-24 lg:grid-cols-2">
          <div>
            <h2 className="text-4xl font-bold tracking-tight">How the agent works</h2>
            <p className="mt-4 max-w-lg text-muted-foreground">
              Two cooperating agents, one goal: get your form filled correctly.
            </p>
            <div className="mt-8 space-y-4">
              <Card className="border-border bg-background/60 p-5">
                <div className="flex items-start gap-3">
                  <span className="mt-1 inline-block h-2.5 w-2.5 rounded-full bg-[hsl(217_90%_65%)] shadow-[0_0_12px_hsl(217_90%_65%)]" />
                  <div>
                    <h3 className="font-semibold">Blue agent — fast scan</h3>
                    <p className="mt-1 text-sm text-muted-foreground">
                      Walks the DOM, resolves labels via <code>label[for]</code>, ARIA, wrappers and placeholders. Returns a structured field list in milliseconds.
                    </p>
                  </div>
                </div>
              </Card>
              <Card className="border-border bg-background/60 p-5">
                <div className="flex items-start gap-3">
                  <span className="mt-1 inline-block h-2.5 w-2.5 rounded-full bg-destructive shadow-[0_0_12px_hsl(var(--destructive))]" />
                  <div>
                    <h3 className="font-semibold">Red agent — deep reasoning</h3>
                    <p className="mt-1 text-sm text-muted-foreground">
                      Sends the field list + your profile to the Umabonakude HF Space, parses a strict JSON response, and falls back gracefully if the agent times out.
                    </p>
                  </div>
                </div>
              </Card>
            </div>
          </div>

          <Card className="border-border bg-background/80 p-6 font-mono text-xs leading-relaxed text-muted-foreground shadow-elegant">
            <div className="mb-3 flex gap-1.5">
              <span className="h-2.5 w-2.5 rounded-full bg-destructive/70" />
              <span className="h-2.5 w-2.5 rounded-full bg-accent/70" />
              <span className="h-2.5 w-2.5 rounded-full bg-primary/70" />
            </div>
            <pre className="whitespace-pre-wrap">{`POST https://sphahh222-umabonaude.hf.space/run/generate_text

{
  "data": [
    "FIELDS:
1. id=\\"uma_0\\" label=\\"Full name\\" type=text
2. id=\\"uma_1\\" label=\\"Email\\"     type=email
3. id=\\"uma_2\\" label=\\"Country\\"   type=select
   options: South Africa, Kenya, Nigeria, ..."
  ]
}

→ [
  {"id":"uma_0","value":"Sipho Dlamini"},
  {"id":"uma_1","value":"sipho@example.com"},
  {"id":"uma_2","value":"South Africa"}
]`}</pre>
          </Card>
        </div>
      </section>

      {/* Install */}
      <section id="install" className="container py-24">
        <div className="mx-auto max-w-3xl">
          <div className="text-center">
            <h2 className="text-4xl font-bold tracking-tight">Install in 60 seconds</h2>
            <p className="mt-4 text-muted-foreground">
              Works in Chrome, Edge, Brave, Arc and any Chromium browser.
            </p>
          </div>

          <Card className="mt-10 border-border bg-card p-8 shadow-elegant">
            <ol className="space-y-4">
              {steps.map((s, i) => (
                <li key={i} className="flex items-start gap-4">
                  <span className="flex h-7 w-7 flex-none items-center justify-center rounded-full bg-gradient-primary text-sm font-semibold text-primary-foreground">
                    {i + 1}
                  </span>
                  <span className="pt-0.5 text-foreground/90">{s}</span>
                </li>
              ))}
            </ol>
            <div className="mt-8 flex flex-col gap-3 sm:flex-row">
              <Button onClick={download} size="lg" className="bg-gradient-primary shadow-elegant">
                <Download className="mr-2 h-5 w-5" />
                {downloading ? "Preparing…" : "Download .zip"}
              </Button>
              <Button variant="outline" size="lg" asChild>
                <a href="https://huggingface.co/spaces/Sphahh222/UMABONAKUDE" target="_blank" rel="noreferrer">
                  <Github className="mr-2 h-5 w-5" />
                  View the AI agent
                </a>
              </Button>
            </div>
          </Card>
        </div>
      </section>

      <footer className="border-t border-border">
        <div className="container flex flex-col items-center justify-between gap-3 py-8 text-sm text-muted-foreground md:flex-row">
          <span>© {new Date().getFullYear()} Umabonakude</span>
          <span>Built with the Umabonakude agent on Hugging Face.</span>
        </div>
      </footer>
    </div>
  );
}
